import {
  Company,
  GovernanceFlag,
  Ownership,
} from "@/lib/types";
import { FundamentalsSeed } from "./fundamentalsBuilder";
import { PriceSeriesOptions } from "./priceSeries";

export interface CompanySeed {
  company: Company;
  fundamentals: FundamentalsSeed;
  price: Omit<PriceSeriesOptions, "seed"> & { seed?: number };
  bookValuePerShare: number;
  forwardPeFactor: number | null; // null => forward PE unavailable (confidence hit)
  industryPe: number | null;
  ownership: Omit<Ownership, "companyId" | "source" | "updatedAt">;
  dividendsPerShareHistory: number[] | null; // most recent first, in rupees; null = no dividend
  governanceFlags: Omit<GovernanceFlag, "id" | "companyId">[];
  missingFields?: Array<"forwardPe" | "promoterPledge" | "latestQuarterCashFlow" | "interestCoverage">;
}

export const COMPANY_SEEDS: CompanySeed[] = [
  {
    company: {
      id: "nimbus-tech",
      ticker: "NIMBUS",
      isin: "INE001A01011",
      companyName: "Nimbus Technologies Ltd",
      exchange: "NSE",
      sector: "IT",
      industry: "IT Services & Consulting",
      marketCap: 118000,
      marketCapCategory: "Large",
      businessDescription:
        "Mid-tier IT services company focused on cloud migration, data engineering and enterprise SaaS implementation for BFSI and retail clients across US and Europe.",
      active: true,
    },
    fundamentals: {
      seed: 101, years: 7,
      latestRevenue: 21500, latestEbitdaMargin: 26, ebitdaMarginSpread: -3,
      latestEps: 68, epsCagr: 19,
      latestRoe: 27, roeSpread: -6,
      latestRoce: 31, roceSpread: -7,
      latestRoa: 18, roaSpread: -4,
      latestEquity: 14200, equityGrowthPct: 18,
      latestDebtToEquity: 0.08, deSpread: 0.1,
      latestInterestCoverage: 42, icSpread: -14,
      latestCfoToPat: 92, cfoToPatSpread: -8,
      latestFcfToPat: 84, fcfToPatSpread: -10,
      salesCagr: 19, profitCagr: 21,
    },
    price: { days: 780, endPrice: 1900, annualDriftPct: 22, volatilityPct: 1.6, baseVolume: 850000, recentVolumeMultiplier: 1.4 },
    bookValuePerShare: 410,
    forwardPeFactor: 0.87,
    industryPe: 27,
    ownership: { period: "Q1FY27", promoterHolding: 61.2, promoterHoldingChange: 0, promoterPledge: 0, fiiHolding: 19.4, fiiChange: 0.6, diiHolding: 12.1, diiChange: 0.3 },
    dividendsPerShareHistory: [14, 12, 10, 8, 7],
    governanceFlags: [],
  },
  {
    company: {
      id: "zenith-retail",
      ticker: "ZENRET",
      isin: "INE002A01022",
      companyName: "Zenith Retail Ventures Ltd",
      exchange: "NSE",
      sector: "Consumer Discretionary",
      industry: "Speciality Retail",
      marketCap: 42000,
      marketCapCategory: "Mid",
      businessDescription:
        "Omnichannel apparel and lifestyle retailer expanding tier-2/3 store footprint alongside a fast-growing online channel.",
      active: true,
    },
    fundamentals: {
      seed: 102, years: 6,
      latestRevenue: 6800, latestEbitdaMargin: 14, ebitdaMarginSpread: -4,
      latestEps: 22, epsCagr: 24,
      latestRoe: 19, roeSpread: -5,
      latestRoce: 21, roceSpread: -6,
      latestRoa: 9, roaSpread: -2,
      latestEquity: 3100, equityGrowthPct: 22,
      latestDebtToEquity: 0.45, deSpread: -0.15,
      latestInterestCoverage: 6.2, icSpread: 1.8,
      latestCfoToPat: 58, cfoToPatSpread: 6,
      latestFcfToPat: 38, fcfToPatSpread: 12,
      salesCagr: 24, profitCagr: 27,
    },
    price: { days: 700, endPrice: 1580, annualDriftPct: 30, volatilityPct: 2.3, baseVolume: 320000, recentVolumeMultiplier: 1.1 },
    bookValuePerShare: 165,
    forwardPeFactor: 0.8,
    industryPe: 38,
    ownership: { period: "Q1FY27", promoterHolding: 54.8, promoterHoldingChange: -0.4, promoterPledge: 0, fiiHolding: 14.2, fiiChange: 1.1, diiHolding: 8.5, diiChange: 0.4 },
    dividendsPerShareHistory: null,
    governanceFlags: [],
  },
  {
    company: {
      id: "rampur-auto",
      ticker: "RAMPAUTO",
      isin: "INE003A01033",
      companyName: "Rampur Auto Components Ltd",
      exchange: "NSE",
      sector: "Auto",
      industry: "Auto Ancillaries",
      marketCap: 26500,
      marketCapCategory: "Mid",
      businessDescription:
        "Precision auto components manufacturer supplying forgings and machined parts to domestic OEMs and export markets, with a growing EV component line.",
      active: true,
    },
    fundamentals: {
      seed: 103, years: 8,
      latestRevenue: 8200, latestEbitdaMargin: 18, ebitdaMarginSpread: -2,
      latestEps: 54, epsCagr: 14,
      latestRoe: 19, roeSpread: -3,
      latestRoce: 22, roceSpread: -3,
      latestRoa: 11, roaSpread: -2,
      latestEquity: 4400, equityGrowthPct: 14,
      latestDebtToEquity: 0.32, deSpread: 0.2,
      latestInterestCoverage: 9.5, icSpread: -2,
      latestCfoToPat: 88, cfoToPatSpread: -6,
      latestFcfToPat: 66, fcfToPatSpread: -8,
      salesCagr: 13, profitCagr: 15,
    },
    price: { days: 900, endPrice: 980, annualDriftPct: 12, volatilityPct: 1.8, baseVolume: 210000, recentVolumeMultiplier: 1.0 },
    bookValuePerShare: 320,
    forwardPeFactor: 0.9,
    industryPe: 22,
    ownership: { period: "Q1FY27", promoterHolding: 58.1, promoterHoldingChange: 0.2, promoterPledge: 0, fiiHolding: 9.8, fiiChange: 0.2, diiHolding: 15.6, diiChange: 0.6 },
    dividendsPerShareHistory: [6, 5.5, 5, 4.5, 4],
    governanceFlags: [],
  },
  {
    company: {
      id: "bharatpur-eng",
      ticker: "BHAREW",
      isin: "INE004A01044",
      companyName: "Bharatpur Engineering Works Ltd",
      exchange: "NSE",
      sector: "Industrials",
      industry: "Capital Goods",
      marketCap: 19800,
      marketCapCategory: "Mid",
      businessDescription:
        "Industrial capital goods manufacturer of pumps, valves and process equipment for water infrastructure and energy projects, with a large executable order book.",
      active: true,
    },
    fundamentals: {
      seed: 104, years: 7,
      latestRevenue: 5100, latestEbitdaMargin: 15, ebitdaMarginSpread: -1.5,
      latestEps: 38, epsCagr: 16,
      latestRoe: 18, roeSpread: -4,
      latestRoce: 20, roceSpread: -4,
      latestRoa: 10, roaSpread: -2,
      latestEquity: 2600, equityGrowthPct: 16,
      latestDebtToEquity: 0.22, deSpread: 0.18,
      latestInterestCoverage: 11, icSpread: -3,
      latestCfoToPat: 74, cfoToPatSpread: -4,
      latestFcfToPat: 60, fcfToPatSpread: -6,
      salesCagr: 14, profitCagr: 16,
    },
    price: { days: 820, endPrice: 640, annualDriftPct: 10, volatilityPct: 1.7, baseVolume: 180000, recentVolumeMultiplier: 0.9 },
    bookValuePerShare: 205,
    forwardPeFactor: 0.88,
    industryPe: 24,
    ownership: { period: "Q1FY27", promoterHolding: 49.6, promoterHoldingChange: 0, promoterPledge: 0, fiiHolding: 7.4, fiiChange: -0.2, diiHolding: 18.9, diiChange: 0.8 },
    dividendsPerShareHistory: [3.5, 3, 3, 2.5, 2],
    governanceFlags: [],
  },
  {
    company: {
      id: "konkan-steel",
      ticker: "KONSTEEL",
      isin: "INE005A01055",
      companyName: "Konkan Steel & Alloys Ltd",
      exchange: "NSE",
      sector: "Metals",
      industry: "Steel",
      marketCap: 15200,
      marketCapCategory: "Mid",
      businessDescription:
        "Integrated steel producer with long-products capacity, exposed to cyclical steel prices and rising input costs; trades at a persistently low multiple.",
      active: true,
    },
    fundamentals: {
      seed: 105, years: 7,
      latestRevenue: 12400, latestEbitdaMargin: 11, ebitdaMarginSpread: 4,
      latestEps: 18, epsCagr: -4,
      latestRoe: 8, roeSpread: 5,
      latestRoce: 9, roceSpread: 6,
      latestRoa: 4, roaSpread: 2,
      latestEquity: 7800, equityGrowthPct: 4,
      latestDebtToEquity: 0.95, deSpread: -0.35,
      latestInterestCoverage: 2.4, icSpread: 1.6,
      latestCfoToPat: 130, cfoToPatSpread: -40,
      latestFcfToPat: 20, fcfToPatSpread: 30,
      salesCagr: 4, profitCagr: -6,
    },
    price: { days: 780, endPrice: 165, annualDriftPct: -6, volatilityPct: 2.6, baseVolume: 640000, recentVolumeMultiplier: 1.2 },
    bookValuePerShare: 210,
    forwardPeFactor: null,
    industryPe: 14,
    ownership: { period: "Q1FY27", promoterHolding: 46.2, promoterHoldingChange: -1.1, promoterPledge: 12.5, fiiHolding: 4.1, fiiChange: -0.6, diiHolding: 9.2, diiChange: -0.4 },
    dividendsPerShareHistory: [1, 1, 1.5, 1.5, 2],
    governanceFlags: [
      { date: "2026-06-15", flagType: "Rapid debt increase", severity: "medium", description: "Gross debt up 28% YoY funding capacity expansion amid weak steel prices.", source: "Annual report FY26", resolved: false },
    ],
    missingFields: ["forwardPe"],
  },
  {
    company: {
      id: "suraksha-consumer",
      ticker: "SURAKSHA",
      isin: "INE006A01066",
      companyName: "Suraksha Consumer Products Ltd",
      exchange: "NSE",
      sector: "FMCG",
      industry: "Household & Personal Care",
      marketCap: 68000,
      marketCapCategory: "Large",
      businessDescription:
        "Household and personal-care FMCG major with a portfolio of market-leading soap, detergent and oral-care brands and pan-India distribution reach.",
      active: true,
    },
    fundamentals: {
      seed: 106, years: 9,
      latestRevenue: 15800, latestEbitdaMargin: 22, ebitdaMarginSpread: -2,
      latestEps: 42, epsCagr: 11,
      latestRoe: 32, roeSpread: -4,
      latestRoce: 36, roceSpread: -5,
      latestRoa: 20, roaSpread: -3,
      latestEquity: 8100, equityGrowthPct: 10,
      latestDebtToEquity: 0.05, deSpread: 0.05,
      latestInterestCoverage: 55, icSpread: -20,
      latestCfoToPat: 98, cfoToPatSpread: -6,
      latestFcfToPat: 90, fcfToPatSpread: -8,
      salesCagr: 10, profitCagr: 12,
    },
    price: { days: 900, endPrice: 1420, annualDriftPct: 11, volatilityPct: 1.2, baseVolume: 410000, recentVolumeMultiplier: 1.0 },
    bookValuePerShare: 145,
    forwardPeFactor: 0.93,
    industryPe: 42,
    ownership: { period: "Q1FY27", promoterHolding: 62.4, promoterHoldingChange: 0, promoterPledge: 0, fiiHolding: 16.8, fiiChange: 0.1, diiHolding: 11.2, diiChange: 0.2 },
    dividendsPerShareHistory: [24, 22, 20, 18, 16],
    governanceFlags: [],
  },
  {
    company: {
      id: "prakash-power",
      ticker: "PRAKPOWER",
      isin: "INE007A01077",
      companyName: "Prakash Power Transmission Ltd",
      exchange: "NSE",
      sector: "Utilities",
      industry: "Power Transmission",
      marketCap: 31000,
      marketCapCategory: "Mid",
      businessDescription:
        "Regulated power transmission utility with long-term tariff-based contracts, stable cash flows and a high dividend payout policy.",
      active: true,
    },
    fundamentals: {
      seed: 107, years: 8,
      latestRevenue: 5200, latestEbitdaMargin: 62, ebitdaMarginSpread: -2,
      latestEps: 12.5, epsCagr: 7,
      latestRoe: 15, roeSpread: -1.5,
      latestRoce: 13, roceSpread: -1,
      latestRoa: 6, roaSpread: -0.5,
      latestEquity: 9200, equityGrowthPct: 7,
      latestDebtToEquity: 1.1, deSpread: 0.2,
      latestInterestCoverage: 3.6, icSpread: -0.4,
      latestCfoToPat: 105, cfoToPatSpread: -10,
      latestFcfToPat: 55, fcfToPatSpread: -15,
      salesCagr: 7, profitCagr: 7,
    },
    price: { days: 850, endPrice: 168, annualDriftPct: 8, volatilityPct: 1.1, baseVolume: 520000, recentVolumeMultiplier: 1.0 },
    bookValuePerShare: 88,
    forwardPeFactor: 0.95,
    industryPe: 16,
    ownership: { period: "Q1FY27", promoterHolding: 65.0, promoterHoldingChange: 0, promoterPledge: 0, fiiHolding: 8.9, fiiChange: 0.1, diiHolding: 14.4, diiChange: 0.3 },
    dividendsPerShareHistory: [7.5, 7, 6.5, 6, 5.5],
    governanceFlags: [],
  },
  {
    company: {
      id: "konark-oil",
      ticker: "KONARKOIL",
      isin: "INE008A01088",
      companyName: "Konark Oil & Gas Ltd",
      exchange: "NSE",
      sector: "Energy",
      industry: "Oil Exploration & Production",
      marketCap: 54000,
      marketCapCategory: "Large",
      businessDescription:
        "Upstream oil and gas producer with domestic block interests; earnings are sensitive to crude price cycles, offset by a conservative balance sheet and steady dividends.",
      active: true,
    },
    fundamentals: {
      seed: 108, years: 8,
      latestRevenue: 24500, latestEbitdaMargin: 34, ebitdaMarginSpread: 6,
      latestEps: 26, epsCagr: 3,
      latestRoe: 14, roeSpread: -2,
      latestRoce: 16, roceSpread: -2,
      latestRoa: 9, roaSpread: -1,
      latestEquity: 21000, equityGrowthPct: 6,
      latestDebtToEquity: 0.18, deSpread: 0.1,
      latestInterestCoverage: 14, icSpread: -3,
      latestCfoToPat: 118, cfoToPatSpread: -15,
      latestFcfToPat: 62, fcfToPatSpread: -10,
      salesCagr: 5, profitCagr: 4,
    },
    price: { days: 850, endPrice: 285, annualDriftPct: 4, volatilityPct: 1.9, baseVolume: 730000, recentVolumeMultiplier: 1.0 },
    bookValuePerShare: 195,
    forwardPeFactor: 0.97,
    industryPe: 11,
    ownership: { period: "Q1FY27", promoterHolding: 51.5, promoterHoldingChange: 0, promoterPledge: 0, fiiHolding: 10.2, fiiChange: -0.3, diiHolding: 22.6, diiChange: 0.5 },
    dividendsPerShareHistory: [11, 10.5, 9, 9.5, 8],
    governanceFlags: [],
  },
  {
    company: {
      id: "udaan-textiles",
      ticker: "UDAANTEX",
      isin: "INE009A01099",
      companyName: "Udaan Textiles Ltd",
      exchange: "BSE",
      sector: "Consumer Discretionary",
      industry: "Textiles",
      marketCap: 2100,
      marketCapCategory: "Small",
      businessDescription:
        "Small-cap textile manufacturer attempting a turnaround via a new export-focused product line after several weak years; balance sheet remains stretched.",
      active: true,
    },
    fundamentals: {
      seed: 109, years: 5,
      latestRevenue: 980, latestEbitdaMargin: 9, ebitdaMarginSpread: -5,
      latestEps: 4.2, epsCagr: 35,
      latestRoe: 11, roeSpread: -9,
      latestRoce: 10, roceSpread: -6,
      latestRoa: 4, roaSpread: -2,
      latestEquity: 480, equityGrowthPct: 8,
      latestDebtToEquity: 1.4, deSpread: 0.3,
      latestInterestCoverage: 1.8, icSpread: -0.6,
      latestCfoToPat: 70, cfoToPatSpread: -30,
      latestFcfToPat: 25, fcfToPatSpread: -10,
      salesCagr: 9, profitCagr: 22,
    },
    price: { days: 600, endPrice: 62, annualDriftPct: 15, volatilityPct: 3.4, baseVolume: 410000, recentVolumeMultiplier: 1.8 },
    bookValuePerShare: 40,
    forwardPeFactor: null,
    industryPe: 20,
    ownership: { period: "Q1FY27", promoterHolding: 41.0, promoterHoldingChange: -2.4, promoterPledge: 38.0, fiiHolding: 1.2, fiiChange: 0, diiHolding: 2.1, diiChange: -0.1 },
    dividendsPerShareHistory: null,
    governanceFlags: [
      { date: "2026-07-02", flagType: "Promoter pledge", severity: "high", description: "Promoter pledge rose to 38% of holding, up from 24% a year ago.", source: "BSE shareholding disclosure", resolved: false },
      { date: "2026-02-20", flagType: "Significant promoter selling", severity: "medium", description: "Promoter stake reduced by 2.4pp over the last two quarters.", source: "BSE shareholding disclosure", resolved: false },
    ],
    missingFields: ["forwardPe", "latestQuarterCashFlow"],
  },
  {
    company: {
      id: "shreeji-realty",
      ticker: "SHREEJI",
      isin: "INE010A01100",
      companyName: "Shreeji Realty Developers Ltd",
      exchange: "BSE",
      sector: "Real Estate",
      industry: "Residential Real Estate",
      marketCap: 3800,
      marketCapCategory: "Small",
      businessDescription:
        "Regional residential real-estate developer with a launch pipeline concentrated in one metro market; earnings are lumpy and project-cycle dependent.",
      active: true,
    },
    fundamentals: {
      seed: 110, years: 5,
      latestRevenue: 1450, latestEbitdaMargin: 24, ebitdaMarginSpread: -6,
      latestEps: 9.5, epsCagr: 18,
      latestRoe: 16, roeSpread: -8,
      latestRoce: 14, roceSpread: -5,
      latestRoa: 6, roaSpread: -2,
      latestEquity: 920, equityGrowthPct: 12,
      latestDebtToEquity: 0.68, deSpread: 0.25,
      latestInterestCoverage: 3.9, icSpread: -1.2,
      latestCfoToPat: 45, cfoToPatSpread: 20,
      latestFcfToPat: 30, fcfToPatSpread: 15,
      salesCagr: 16, profitCagr: 19,
    },
    price: { days: 620, endPrice: 118, annualDriftPct: 20, volatilityPct: 3.0, baseVolume: 260000, recentVolumeMultiplier: 1.3 },
    bookValuePerShare: 75,
    forwardPeFactor: null,
    industryPe: 25,
    ownership: { period: "Q1FY27", promoterHolding: 57.3, promoterHoldingChange: 0.5, promoterPledge: 0, fiiHolding: 2.8, fiiChange: 0.3, diiHolding: 3.9, diiChange: 0.2 },
    dividendsPerShareHistory: [1, 0.5, 0, 0, 0],
    governanceFlags: [],
    missingFields: ["forwardPe", "promoterPledge"],
  },
  {
    company: {
      id: "uttar-sahakari-bank",
      ticker: "USBANK",
      isin: "INE011A01111",
      companyName: "Uttar Sahakari Bank Ltd",
      exchange: "NSE",
      sector: "Banks",
      industry: "Private Sector Bank",
      marketCap: 142000,
      marketCapCategory: "Large",
      businessDescription:
        "Well-capitalized private-sector bank with a granular retail and MSME loan book, strong CASA franchise and industry-leading asset quality.",
      active: true,
    },
    fundamentals: {
      seed: 111, years: 8,
      latestRevenue: 38000, latestEbitdaMargin: 0, ebitdaMarginSpread: 0,
      latestEps: 62, epsCagr: 18,
      latestRoe: 17, roeSpread: -3,
      latestRoce: 0, roceSpread: 0,
      latestRoa: 1.9, roaSpread: -0.3,
      latestEquity: 68000, equityGrowthPct: 15,
      latestDebtToEquity: 0, deSpread: 0,
      latestInterestCoverage: 0, icSpread: 0,
      latestCfoToPat: 0, cfoToPatSpread: 0,
      latestFcfToPat: 0, fcfToPatSpread: 0,
      salesCagr: 17, profitCagr: 19,
      bank: {
        latestNim: 4.4, latestGnpa: 1.1, latestNnpa: 0.3, latestProvisionCoverageRatio: 78,
        latestCapitalAdequacyRatio: 17.5, latestCostToIncome: 42, latestCreditGrowth: 19, gnpaSpread: -0.8,
      },
    },
    price: { days: 900, endPrice: 1680, annualDriftPct: 17, volatilityPct: 1.5, baseVolume: 610000, recentVolumeMultiplier: 1.1 },
    bookValuePerShare: 420,
    forwardPeFactor: 0.87,
    industryPe: 24,
    ownership: { period: "Q1FY27", promoterHolding: 0, promoterHoldingChange: 0, promoterPledge: 0, fiiHolding: 42.1, fiiChange: 0.8, diiHolding: 31.4, diiChange: 0.6 },
    dividendsPerShareHistory: [8, 7, 6, 5, 4],
    governanceFlags: [],
  },
  {
    company: {
      id: "vidya-finance",
      ticker: "VIDYAFIN",
      isin: "INE012A01122",
      companyName: "Vidya Finance Corporation Ltd",
      exchange: "NSE",
      sector: "NBFC",
      industry: "Diversified NBFC",
      marketCap: 9600,
      marketCapCategory: "Mid",
      businessDescription:
        "Mid-sized NBFC focused on vehicle and SME lending, facing rising delinquencies in its unsecured book after rapid loan growth in recent years.",
      active: true,
    },
    fundamentals: {
      seed: 112, years: 6,
      latestRevenue: 3200, latestEbitdaMargin: 0, ebitdaMarginSpread: 0,
      latestEps: 14, epsCagr: -8,
      latestRoe: 9, roeSpread: 6,
      latestRoce: 0, roceSpread: 0,
      latestRoa: 1.1, roaSpread: 0.6,
      latestEquity: 5200, equityGrowthPct: 10,
      latestDebtToEquity: 0, deSpread: 0,
      latestInterestCoverage: 0, icSpread: 0,
      latestCfoToPat: 0, cfoToPatSpread: 0,
      latestFcfToPat: 0, fcfToPatSpread: 0,
      salesCagr: 14, profitCagr: -5,
      bank: {
        latestNim: 6.8, latestGnpa: 4.6, latestNnpa: 2.1, latestProvisionCoverageRatio: 52,
        latestCapitalAdequacyRatio: 16.2, latestCostToIncome: 48, latestCreditGrowth: 11, gnpaSpread: 2.6,
      },
    },
    price: { days: 700, endPrice: 142, annualDriftPct: -8, volatilityPct: 2.8, baseVolume: 380000, recentVolumeMultiplier: 1.4 },
    bookValuePerShare: 160,
    forwardPeFactor: null,
    industryPe: 13,
    ownership: { period: "Q1FY27", promoterHolding: 38.5, promoterHoldingChange: -1.2, promoterPledge: 5.0, fiiHolding: 12.4, fiiChange: -1.5, diiHolding: 9.8, diiChange: -0.6 },
    dividendsPerShareHistory: [2, 2, 1.8, 1.5, 1.5],
    governanceFlags: [
      { date: "2026-08-01", flagType: "Sharp earnings deterioration", severity: "medium", description: "Q1FY27 profit fell 22% YoY as credit costs rose in the unsecured lending book.", source: "Q1FY27 results", resolved: false },
    ],
  },
  {
    company: {
      id: "kavach-life",
      ticker: "KAVACHLIFE",
      isin: "INE013A01133",
      companyName: "Kavach Life Insurance Ltd",
      exchange: "NSE",
      sector: "Insurance",
      industry: "Life Insurance",
      marketCap: 76000,
      marketCapCategory: "Large",
      businessDescription:
        "Private life insurer with a diversified agency and bancassurance distribution mix and a growing protection and annuity product share.",
      active: true,
    },
    fundamentals: {
      seed: 113, years: 7,
      latestRevenue: 9800, latestEbitdaMargin: 0, ebitdaMarginSpread: 0,
      latestEps: 16, epsCagr: 16,
      latestRoe: 20, roeSpread: -3,
      latestRoce: 0, roceSpread: 0,
      latestRoa: 2.4, roaSpread: -0.3,
      latestEquity: 11500, equityGrowthPct: 13,
      latestDebtToEquity: 0, deSpread: 0,
      latestInterestCoverage: 0, icSpread: 0,
      latestCfoToPat: 0, cfoToPatSpread: 0,
      latestFcfToPat: 0, fcfToPatSpread: 0,
      salesCagr: 15, profitCagr: 17,
      bank: {
        latestNim: 0, latestGnpa: 0, latestNnpa: 0, latestProvisionCoverageRatio: 0,
        latestCapitalAdequacyRatio: 195, latestCostToIncome: 0, latestCreditGrowth: 0, gnpaSpread: 0,
      },
    },
    price: { days: 780, endPrice: 720, annualDriftPct: 15, volatilityPct: 1.7, baseVolume: 290000, recentVolumeMultiplier: 1.0 },
    bookValuePerShare: 95,
    forwardPeFactor: 0.88,
    industryPe: 55,
    ownership: { period: "Q1FY27", promoterHolding: 62.6, promoterHoldingChange: 0, promoterPledge: 0, fiiHolding: 21.3, fiiChange: 0.4, diiHolding: 8.1, diiChange: 0.2 },
    dividendsPerShareHistory: [2.5, 2, 1.8, 1.5, 1.2],
    governanceFlags: [],
  },
  {
    company: {
      id: "ashoka-life-sciences",
      ticker: "ASHOKAPHARMA",
      isin: "INE014A01144",
      companyName: "Ashoka Life Sciences Ltd",
      exchange: "NSE",
      sector: "Pharma",
      industry: "Specialty Pharmaceuticals",
      marketCap: 48000,
      marketCapCategory: "Mid",
      businessDescription:
        "Specialty pharma company with a growing US generics pipeline and a domestic branded formulations business, backed by consistent R&D reinvestment.",
      active: true,
    },
    fundamentals: {
      seed: 114, years: 8,
      latestRevenue: 7600, latestEbitdaMargin: 28, ebitdaMarginSpread: -4,
      latestEps: 46, epsCagr: 20,
      latestRoe: 24, roeSpread: -5,
      latestRoce: 27, roceSpread: -6,
      latestRoa: 15, roaSpread: -3,
      latestEquity: 4200, equityGrowthPct: 17,
      latestDebtToEquity: 0.12, deSpread: 0.15,
      latestInterestCoverage: 28, icSpread: -8,
      latestCfoToPat: 95, cfoToPatSpread: -10,
      latestFcfToPat: 82, fcfToPatSpread: -14,
      salesCagr: 18, profitCagr: 21,
    },
    price: { days: 850, endPrice: 1360, annualDriftPct: 21, volatilityPct: 1.9, baseVolume: 260000, recentVolumeMultiplier: 1.2 },
    bookValuePerShare: 260,
    forwardPeFactor: 0.85,
    industryPe: 30,
    ownership: { period: "Q1FY27", promoterHolding: 55.4, promoterHoldingChange: 0.3, promoterPledge: 0, fiiHolding: 18.6, fiiChange: 0.9, diiHolding: 10.4, diiChange: 0.5 },
    dividendsPerShareHistory: [5, 4, 3.5, 3, 2.5],
    governanceFlags: [],
  },
  {
    company: {
      id: "girivan-formulations",
      ticker: "GIRIVAN",
      isin: "INE015A01155",
      companyName: "Girivan Formulations Ltd",
      exchange: "BSE",
      sector: "Pharma",
      industry: "Generic Pharmaceuticals",
      marketCap: 8200,
      marketCapCategory: "Mid",
      businessDescription:
        "Domestic-focused generics manufacturer currently under a regulatory and governance cloud following its statutory auditor's resignation.",
      active: true,
    },
    fundamentals: {
      seed: 115, years: 6,
      latestRevenue: 2600, latestEbitdaMargin: 19, ebitdaMarginSpread: 3,
      latestEps: 12, epsCagr: -10,
      latestRoe: 13, roeSpread: 4,
      latestRoce: 15, roceSpread: 3,
      latestRoa: 7, roaSpread: 2,
      latestEquity: 1800, equityGrowthPct: 6,
      latestDebtToEquity: 0.4, deSpread: -0.1,
      latestInterestCoverage: 5.5, icSpread: 2,
      latestCfoToPat: 60, cfoToPatSpread: 20,
      latestFcfToPat: 35, fcfToPatSpread: 15,
      salesCagr: 8, profitCagr: -6,
    },
    price: { days: 650, endPrice: 210, annualDriftPct: -12, volatilityPct: 3.1, baseVolume: 190000, recentVolumeMultiplier: 1.6 },
    bookValuePerShare: 150,
    forwardPeFactor: null,
    industryPe: 26,
    ownership: { period: "Q1FY27", promoterHolding: 48.9, promoterHoldingChange: -0.8, promoterPledge: 6.2, fiiHolding: 3.1, fiiChange: -0.9, diiHolding: 4.5, diiChange: -0.3 },
    dividendsPerShareHistory: [1.5, 1.5, 1.5, 1.2, 1],
    governanceFlags: [
      { date: "2026-08-20", flagType: "Auditor resignation", severity: "high", description: "Statutory auditor resigned mid-term citing inability to obtain sufficient audit evidence on certain related-party transactions.", source: "BSE exchange filing", resolved: false },
      { date: "2026-08-22", flagType: "Unusual related-party transactions", severity: "high", description: "Auditor's resignation letter flagged unexplained related-party loans advanced in Q4FY26.", source: "BSE exchange filing", resolved: false },
    ],
  },
];
